[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "peakrdl-pybind"
version = "0.1.0"
description = "PeakRDL backend that generates PyBind11 register access modules"
readme = "README.md"
authors = [
  { name = "PeakRDL PyBind Contributors" }
]
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
  "systemrdl-compiler>=1.25",
  "jinja2>=3.1",
  "click>=8",
]

[project.optional-dependencies]
test = [
  "pytest>=7",
]

[project.scripts]
peakrdl-pybind = "peakrdl_pybind.cli:main"

[project.entry-points."systemrdl_backends"]
peakrdl_pybind = "peakrdl_pybind.backend:PyBindBackend"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"peakrdl_pybind" = ["templates/*.jinja"]
