[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "peakrdl-pybind"
version = "0.1.0"
description = "PeakRDL backend that generates PyBind11 register access modules"
readme = "README.md"
authors = [
  {name = "PeakRDL Contributors"}
]
license = {file = "LICENSE"}
requires-python = ">=3.9"
dependencies = [
  "peakrdl>=1.0",
  "systemrdl-compiler>=1.28",
  "jinja2>=3.1",
  "click>=8.1",
  "packaging>=23"
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-regressions"
]

[project.entry-points."systemrdl_backends"]
peakrdl_pybind = "peakrdl_pybind.backend:PyBindBackend"

[project.scripts]
peakrdl-pybind = "peakrdl_pybind.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra"
pythonpath = ["src"]
