"""
example_soc - Generated SoC register map
Generated by PeakRDL-pybind11 from SystemRDL

This module provides Python access to the example_soc register map.
"""

try:
    from ._example_soc_native import *
except ImportError as e:
    import sys
    print(f"Error importing native module: {e}", file=sys.stderr)
    print("You need to build the C++ extension first:", file=sys.stderr)
    print(f"  cd <output_dir> && python setup.py build_ext --inplace", file=sys.stderr)
    raise

__all__ = ['example_soc_t', 'Master', 'create']

def create():
    """
    Create a new instance of the example_soc register map
    
    Returns:
        example_soc_t: A new SoC instance
    
    Example:
        >>> soc = create()
        >>> from peakrdl_pybind11.masters import MockMaster
        >>> soc.attach_master(MockMaster())
    """
    return example_soc_t()