name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, format, test]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -e .
      
      - name: Build package
        run: python -m build --no-isolation
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist/
  
  lint:
    uses: ./.github/workflows/lint.yml
  
  typecheck:
    uses: ./.github/workflows/typecheck.yml
  
  format:
    uses: ./.github/workflows/format.yml
  
  test:
    uses: ./.github/workflows/test.yml
